### ISSUE TITLE
dalao

### ISSUE THREAD

**Issue by 330327199910051733** [Zhouzp2115/secure-infer#1]
dalao 能不能加个练习方式

**Comment by Zhouzp2115** [comment]
怎么联系

**Comment by 330327199910051733** [comment]
大佬这是我的QQ：455049386 ，谢谢大佬
&nbsp;


大侠
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月25日(星期二) 中午12:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Zhouzp2115/secure-infer] dalao (Issue #1)





 
怎么联系
